In [1]:
import pandas as pd 
import numpy as np 
%matplotlib inline 
import matplotlib.pyplot as plt
import sklearn
import datetime
print(f"Using Sklearn Version: {sklearn.__version__}")
print(f"Last Updated: {datetime.datetime.now()}")

Using Sklearn Version: 1.7.2
Last Updated: 2026-03-03 22:05:10.045589

In [2]:
heart_disease = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv")
heart_disease.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
X = heart_disease.drop('target',axis=1)
y = heart_disease['target']
X.tail(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [4]:
y.head(5), y.value_counts()

(0    1
 1    1
 2    1
 3    1
 4    1
 Name: target, dtype: int64,
 target
 1    165
 0    138
 Name: count, dtype: int64)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X,y,test_size = 0.25,random_state=42)

In [6]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((227, 13), (227,), (76, 13), (76,))

In [7]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [8]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [9]:
model.fit(X = X_train, y = y_train)

RandomForestClassifier()

In [10]:
y_preds = model.predict(X = X_test)
y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [11]:
# Evaluate 
# Training Data 
train_acc = model.score(X = X_train, y = y_train)
print(f"Accuracy on the training dataset is: {train_acc*100:.2f}%")

# Testing Data 
test_acc = model.score(X = X_test, y = y_test)
print(f"Accuracy on the testing dataset is: {test_acc*100:.2f}%")

# More Evaluation Method 
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
classi_repo = classification_report(y_test,y_preds)
print(f"Classification Report of the model is: {classi_repo}")
confu_mat = confusion_matrix(y_test,y_preds)
print(f"Confusion Matrix of the model is: {confu_mat}")
acc_score = accuracy_score(y_test,y_preds)
print(f"Accuracy score of the model is: {acc_score*100:.2f}%")

Accuracy on the training dataset is: 100.00%
Accuracy on the testing dataset is: 85.53%
Classification Report of the model is:               precision    recall  f1-score   support

           0       0.88      0.80      0.84        35
           1       0.84      0.90      0.87        41

    accuracy                           0.86        76
   macro avg       0.86      0.85      0.85        76
weighted avg       0.86      0.86      0.85        76

Confusion Matrix of the model is: [[28  7]
 [ 4 37]]
Accuracy score of the model is: 85.53%

In [12]:
## Experimenting 
np.random.seed(42)
for n in range(200,475,25): 
    print(f"Trying with {n} estimators...")
    model = RandomForestClassifier(n_estimators = n).fit(X = X_train,y = y_train)
    print(f"Estimators accuracy after tuning hyperparameter --> {model.score(X = X_test,y = y_test)*100:.2f}%")

    ## Cross Validation 
    from sklearn.model_selection import cross_val_score
    cross_val_mean = np.mean(cross_val_score(model,X,y,cv = 10 ))
    print(f"Estimators accuracy after 10-fold cross-validation --> {cross_val_mean*100:.2f}%")
    
    print("")

Trying with 200 estimators...
Estimators accuracy after tuning hyperparameter --> 82.89%
Estimators accuracy after 10-fold cross-validation --> 83.82%

Trying with 225 estimators...
Estimators accuracy after tuning hyperparameter --> 84.21%
Estimators accuracy after 10-fold cross-validation --> 83.46%

Trying with 250 estimators...
Estimators accuracy after tuning hyperparameter --> 84.21%
Estimators accuracy after 10-fold cross-validation --> 83.47%

Trying with 275 estimators...
Estimators accuracy after tuning hyperparameter --> 84.21%
Estimators accuracy after 10-fold cross-validation --> 84.47%

Trying with 300 estimators...
Estimators accuracy after tuning hyperparameter --> 84.21%
Estimators accuracy after 10-fold cross-validation --> 82.47%

Trying with 325 estimators...
Estimators accuracy after tuning hyperparameter --> 84.21%
Estimators accuracy after 10-fold cross-validation --> 82.82%

Trying with 350 estimators...
Estimators accuracy after tuning hyperparameter --> 82.89%
Estimators accuracy after 10-fold cross-validation --> 82.81%

Trying with 375 estimators...
Estimators accuracy after tuning hyperparameter --> 81.58%
Estimators accuracy after 10-fold cross-validation --> 82.80%

Trying with 400 estimators...
Estimators accuracy after tuning hyperparameter --> 82.89%
Estimators accuracy after 10-fold cross-validation --> 83.14%

Trying with 425 estimators...
Estimators accuracy after tuning hyperparameter --> 84.21%
Estimators accuracy after 10-fold cross-validation --> 83.13%

Trying with 450 estimators...
Estimators accuracy after tuning hyperparameter --> 84.21%
Estimators accuracy after 10-fold cross-validation --> 83.47%

In [13]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 450,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [14]:
# Automatic Experiments using GridSearchCV
np.random.seed(42)
from sklearn.model_selection import GridSearchCV

param_grid = {"n_estimators" : [n for n in range(200,475,25)]}

grid = GridSearchCV(estimator = RandomForestClassifier(),
                   param_grid = param_grid, 
                   cv = 10,
                   verbose = 1) 
grid.fit(X,y)

print(f"The best hyperparameter values are: {grid.best_params_}")
print(f"With a values with --> {grid.best_score_ * 100 :.2f}% ")

Fitting 10 folds for each of 11 candidates, totalling 110 fits
The best hyperparameter values are: {'n_estimators': 425}
With a values with --> 84.14%

In [15]:
model = grid.best_estimator_
model

RandomForestClassifier(n_estimators=425)

In [16]:
print(f"Best score of the model on a single split dataset is : {grid.best_score_*100:.2f}%")

Best score of the model on a single split dataset is : 84.14%

In [17]:
## Saving model to a file 
import pickle
pickle.dump(model,open("random_forest_classifier_one","wb"))

In [18]:
saved_model = pickle.load(open("random_forest_classifier_one","rb"))
print(f"Loaded Model on a single split dataset: {saved_model.score(X_test,y_test)*100:.2f}%")

Loaded Model on a single split dataset: 100.00%